"""setup

Revision ID: 6301c4242caf
Revises: 
Create Date: 2023-06-10 14:06:14.242529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6301c4242caf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_samples',
    sa.Column('icao_id', sa.String(), nullable=False),
    sa.Column('sample_entry_date_utc', sa.DateTime(), nullable=False),
    sa.Column('flight', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude_ft', sa.Integer(), nullable=True),
    sa.Column('alt_change_ft_per_min', sa.Integer(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('ground_speed_knots', sa.Float(), nullable=True),
    sa.Column('nav_modes', sa.String(), nullable=True),
    sa.Column('emitter_category', sa.String(), nullable=True),
    sa.Column('aircraft_type', sa.String(), nullable=True),
    sa.Column('aircraft_registration', sa.String(), nullable=True),
    sa.Column('flag', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('rssi', sa.Float(), nullable=True),
    sa.Column('emergency', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('icao_id', 'sample_entry_date_utc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight_samples')
    # ### end Alembic commands ###
