"""presentation

Revision ID: 146369f82cbd
Revises: 92f5f2e783a8
Create Date: 2023-10-25 17:21:27.755648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146369f82cbd'
down_revision = '92f5f2e783a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_flight_aggregates',
    sa.Column('sample_date', sa.Date(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('day_and_number', sa.String(), nullable=False),
    sa.Column('total_unique_flights', sa.Integer(), nullable=False),
    sa.Column('max_aircraft', sa.Integer(), nullable=False),
    sa.Column('avg_aircraft', sa.Float(), nullable=False),
    sa.Column('min_aircraft', sa.Integer(), nullable=False),
    sa.Column('avg_ground_speed_knots', sa.Float(), nullable=False),
    sa.Column('min_ground_speed_knots', sa.Float(), nullable=False),
    sa.Column('max_ground_speed_knots', sa.Float(), nullable=False),
    sa.Column('max_speed_aircraft_type', sa.String(), nullable=True),
    sa.Column('max_speed_aircraft_registration', sa.String(), nullable=True),
    sa.Column('max_speed_flight', sa.String(), nullable=True),
    sa.Column('avg_altitude_ft', sa.Float(), nullable=False),
    sa.Column('max_altitude_ft', sa.Integer(), nullable=False),
    sa.Column('max_alt_aircraft_type', sa.String(), nullable=True),
    sa.Column('max_alt_aircraft_registration', sa.String(), nullable=True),
    sa.Column('max_alt_flight', sa.String(), nullable=True),
    sa.Column('max_climb_rate_ft_per_min', sa.Integer(), nullable=False),
    sa.Column('max_climb_aircraft_type', sa.String(), nullable=True),
    sa.Column('max_climb_aircraft_registration', sa.String(), nullable=True),
    sa.Column('max_climb_flight', sa.String(), nullable=True),
    sa.Column('max_descent_rate_ft_per_min', sa.Integer(), nullable=False),
    sa.Column('max_descent_aircraft_type', sa.String(), nullable=True),
    sa.Column('max_descent_aircraft_registration', sa.String(), nullable=True),
    sa.Column('max_descent_flight', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('sample_date')
    )
    op.create_table('flight_emergencies',
    sa.Column('icao_id', sa.String(), nullable=False),
    sa.Column('sample_entry_date_utc', sa.DateTime(), nullable=False),
    sa.Column('flight', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude_ft', sa.Integer(), nullable=True),
    sa.Column('alt_change_ft_per_min', sa.Integer(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('ground_speed_knots', sa.Float(), nullable=True),
    sa.Column('nav_modes', sa.String(), nullable=True),
    sa.Column('emitter_category', sa.String(), nullable=True),
    sa.Column('aircraft_type', sa.String(), nullable=True),
    sa.Column('aircraft_registration', sa.String(), nullable=True),
    sa.Column('flag', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('rssi', sa.Float(), nullable=True),
    sa.Column('emergency', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('icao_id', 'sample_entry_date_utc')
    )
    op.create_table('monthly_flight_aggregates',
    sa.Column('month_start_date', sa.Date(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('month_and_year', sa.String(), nullable=False),
    sa.Column('short_month_year', sa.String(), nullable=False),
    sa.Column('total_unique_flights', sa.Integer(), nullable=False),
    sa.Column('max_aircraft', sa.Integer(), nullable=False),
    sa.Column('avg_aircraft', sa.Float(), nullable=False),
    sa.Column('min_aircraft', sa.Integer(), nullable=False),
    sa.Column('avg_ground_speed_knots', sa.Float(), nullable=False),
    sa.Column('min_ground_speed_knots', sa.Float(), nullable=False),
    sa.Column('max_ground_speed_knots', sa.Float(), nullable=False),
    sa.Column('max_speed_aircraft_type', sa.String(), nullable=True),
    sa.Column('max_speed_aircraft_registration', sa.String(), nullable=True),
    sa.Column('max_speed_flight', sa.String(), nullable=True),
    sa.Column('avg_altitude_ft', sa.Float(), nullable=False),
    sa.Column('max_altitude_ft', sa.Integer(), nullable=False),
    sa.Column('max_alt_aircraft_type', sa.String(), nullable=True),
    sa.Column('max_alt_aircraft_registration', sa.String(), nullable=True),
    sa.Column('max_alt_flight', sa.String(), nullable=True),
    sa.Column('max_climb_rate_ft_per_min', sa.Integer(), nullable=False),
    sa.Column('max_climb_aircraft_type', sa.String(), nullable=True),
    sa.Column('max_climb_aircraft_registration', sa.String(), nullable=True),
    sa.Column('max_climb_flight', sa.String(), nullable=True),
    sa.Column('max_descent_rate_ft_per_min', sa.Integer(), nullable=False),
    sa.Column('max_descent_aircraft_type', sa.String(), nullable=True),
    sa.Column('max_descent_aircraft_registration', sa.String(), nullable=True),
    sa.Column('max_descent_flight', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('month_start_date')
    )
    op.create_table('recent_flight_samples',
    sa.Column('icao_id', sa.String(), nullable=False),
    sa.Column('sample_entry_date_utc', sa.DateTime(), nullable=False),
    sa.Column('flight', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude_ft', sa.Integer(), nullable=True),
    sa.Column('alt_change_ft_per_min', sa.Integer(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('ground_speed_knots', sa.Float(), nullable=True),
    sa.Column('nav_modes', sa.String(), nullable=True),
    sa.Column('emitter_category', sa.String(), nullable=True),
    sa.Column('aircraft_type', sa.String(), nullable=True),
    sa.Column('aircraft_registration', sa.String(), nullable=True),
    sa.Column('flag', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('rssi', sa.Float(), nullable=True),
    sa.Column('emergency', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('icao_id', 'sample_entry_date_utc')
    )
    op.create_table('weekly_flight_aggregates',
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('week_of_year', sa.Integer(), nullable=False),
    sa.Column('total_unique_flights', sa.Integer(), nullable=False),
    sa.Column('max_aircraft', sa.Integer(), nullable=False),
    sa.Column('avg_aircraft', sa.Float(), nullable=False),
    sa.Column('min_aircraft', sa.Integer(), nullable=False),
    sa.Column('avg_ground_speed_knots', sa.Float(), nullable=False),
    sa.Column('min_ground_speed_knots', sa.Float(), nullable=False),
    sa.Column('max_ground_speed_knots', sa.Float(), nullable=False),
    sa.Column('max_speed_aircraft_type', sa.String(), nullable=True),
    sa.Column('max_speed_aircraft_registration', sa.String(), nullable=True),
    sa.Column('max_speed_flight', sa.String(), nullable=True),
    sa.Column('avg_altitude_ft', sa.Float(), nullable=False),
    sa.Column('max_altitude_ft', sa.Integer(), nullable=False),
    sa.Column('max_alt_aircraft_type', sa.String(), nullable=True),
    sa.Column('max_alt_aircraft_registration', sa.String(), nullable=True),
    sa.Column('max_alt_flight', sa.String(), nullable=True),
    sa.Column('max_climb_rate_ft_per_min', sa.Integer(), nullable=False),
    sa.Column('max_climb_aircraft_type', sa.String(), nullable=True),
    sa.Column('max_climb_aircraft_registration', sa.String(), nullable=True),
    sa.Column('max_climb_flight', sa.String(), nullable=True),
    sa.Column('max_descent_rate_ft_per_min', sa.Integer(), nullable=False),
    sa.Column('max_descent_aircraft_type', sa.String(), nullable=True),
    sa.Column('max_descent_aircraft_registration', sa.String(), nullable=True),
    sa.Column('max_descent_flight', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('week_start_date')
    )
    with op.batch_alter_table('flight_aggregates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_ground_speed_knots', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('min_ground_speed_knots', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('max_ground_speed_knots', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('max_speed_aircraft_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('max_speed_aircraft_registration', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('max_speed_flight', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('avg_altitude_ft', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('max_altitude_ft', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('max_alt_aircraft_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('max_alt_aircraft_registration', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('max_alt_flight', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('max_climb_rate_ft_per_min', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('max_climb_aircraft_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('max_climb_aircraft_registration', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('max_climb_flight', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('max_descent_rate_ft_per_min', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('max_descent_aircraft_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('max_descent_aircraft_registration', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('max_descent_flight', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight_aggregates', schema=None) as batch_op:
        batch_op.drop_column('max_descent_flight')
        batch_op.drop_column('max_descent_aircraft_registration')
        batch_op.drop_column('max_descent_aircraft_type')
        batch_op.drop_column('max_descent_rate_ft_per_min')
        batch_op.drop_column('max_climb_flight')
        batch_op.drop_column('max_climb_aircraft_registration')
        batch_op.drop_column('max_climb_aircraft_type')
        batch_op.drop_column('max_climb_rate_ft_per_min')
        batch_op.drop_column('max_alt_flight')
        batch_op.drop_column('max_alt_aircraft_registration')
        batch_op.drop_column('max_alt_aircraft_type')
        batch_op.drop_column('max_altitude_ft')
        batch_op.drop_column('avg_altitude_ft')
        batch_op.drop_column('max_speed_flight')
        batch_op.drop_column('max_speed_aircraft_registration')
        batch_op.drop_column('max_speed_aircraft_type')
        batch_op.drop_column('max_ground_speed_knots')
        batch_op.drop_column('min_ground_speed_knots')
        batch_op.drop_column('avg_ground_speed_knots')

    op.drop_table('weekly_flight_aggregates')
    op.drop_table('recent_flight_samples')
    op.drop_table('monthly_flight_aggregates')
    op.drop_table('flight_emergencies')
    op.drop_table('daily_flight_aggregates')
    # ### end Alembic commands ###
